// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJdzD5HORCKNP6x-DAeCxOdP1hkv2bPXk',
    appId: '1:70710236402:web:ff55b78c657421690cec6b',
    messagingSenderId: '70710236402',
    projectId: 'spectrum-ph',
    authDomain: 'spectrum-ph.firebaseapp.com',
    storageBucket: 'spectrum-ph.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEZ2NqrRWtglp11c56Azcak64vzMMCRyg',
    appId: '1:70710236402:android:5628ffd8f21f3a4a0cec6b',
    messagingSenderId: '70710236402',
    projectId: 'spectrum-ph',
    storageBucket: 'spectrum-ph.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5zMJFLsnJI3MKIGyVmKU4KxnhxUugk-M',
    appId: '1:70710236402:ios:caf95a9cdb6d9e0c0cec6b',
    messagingSenderId: '70710236402',
    projectId: 'spectrum-ph',
    storageBucket: 'spectrum-ph.firebasestorage.app',
    iosBundleId: 'com.example.spectrum',
  );
}
